# Generated by Django 5.2 on 2025-04-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourclients',
            options={'verbose_name_plural': 'Our Clients'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='Testmonies/Users/'),
        ),
    ]
