# Generated by Django 5.2 on 2025-04-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_ourclients_options_alter_services_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Team/')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('linkedlin', models.TextField()),
            ],
        ),
    ]
