# Generated by Django 5.2 on 2025-06-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_contactmessage_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='Quotes/'),
        ),
    ]
